require("adrian/monitors")
require("adrian/autostart")
require("adrian/env")
require("adrian/look-and-feel")
require("adrian/input")
require("adrian/keybinds")
require("adrian/windows-and-workspaces")
require("adrian/layout")